var five = 5;
var ten = 10;
console.log("Test1: Five is equal to 5");
console.log(five == 5);
console.log("\nTest2: Ten is equal to 10");
console.log(ten == 10);
console.log("\nTest3: 5 is not equal to 10");
console.log(five != 10);
console.log("\nTest4: 10 is grater than 5");
console.log(ten > 5);
console.log("\nTest5: 5 less than 10");
console.log(5 < 10);
console.log("\nTest6: 5 grater than 10");
console.log(5 > 10);
console.log("\nTest7: 10 less than 5");
console.log(ten < five);
console.log("\nTest8: 5 is equal to 10");
console.log(five == ten);
console.log("\nTest9: 5 is not equal to five");
console.log(5 != five);
console.log("\nTest10: Ten is not equal 10");
console.log(ten != 10);
